# Generated by Django 2.0.1 on 2018-02-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='sector',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='companies',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sectors',
            field=models.TextField(default=''),
        ),
    ]
