# Generated by Django 2.0.1 on 2018-03-03 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180302_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='days_old',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)]),
        ),
    ]
