# Generated by Django 2.0.1 on 2018-03-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userpreferences_days_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='current_price',
        ),
    ]
